resources:
  repositories:
    - repository: pf
      type: git
      name: CVX-DevOps/ADOPipeline
      ref: refs/tags/latest-stable

########################################################
# WARNING: Removing/Modifying the following Parameters
# may cause errors with your pipeline!
########################################################
parameters:
  - name: forceUpdate
    displayName: Update Pipeline
    type: boolean
    default: false
  - name: deployEnvironment
    displayName: Deployment Environment
    type: string
    default: test
    values:
      - test
  - name: deploymentType
    displayName: Deployment Type
    type: string
    default: code_only
    values:
      - code_only
      - full
  - name: isSastEnabled
    displayName: SAST Scan
    type: boolean
    default: false
  - name: automationFilter
    displayName: Automation Suite
    type: string
    default: BuildVerification
    values:
      - BuildVerification
      - AllTestRun 
########################################################

trigger: 
  - test

stages:
  - template: pipeline.yml@pf
    parameters:
      ${{ insert }}: ${{ parameters }} # DO NOT MODIFY
      serviceId: 25752
      releaseBranch: ' ' # prevents a prod build from getting deployed to test environmnent
      projects:
        - name: mit_pwa
          outputPath: "/dist/mit-pwa"
          type: node
          nodeVersion: "18.19.x"
          setEnvironment: true

          isBuildActive: true
          isDeployActive: true
          isSASTScanActive: ${{ parameters.isSastEnabled }}
          isDASTScanActive: false
          dependabot: false
          sonarqube:
            sqExclusions: ''
            additionalProperties: 'sonar.branch.name=${{ variables.branchName }}'

          playbook: "pipeline/playbook.yml"
          extraAnsibleVars: |
            deployment_type: "${{ parameters.deploymentType }}"

        - name: Playwright_Test
          dependsOn: 
          - mit_pwa
          type: test
          timeoutInMinutes: 240
          tests:
          - name: 'Automation'
            checkout:
            - project: 'GUIT.FWE.AI_Inspections' # Name of the project.
              repo: 'mit-playwright' # Name of the repository.  
              branch: 'feature/mi-automation'
            type: playwright.net
            coreVersion: '6.x'
            playwrightWorkingDirectory: 'mit-playwright'
            testResultsFolder: 'mit-playwright/bin/Debug/net6.0'
            filePath:  "mit-playwright/MobileInspection.csproj"
            testArguments: "--filter TestCategory=${{ parameters.automationFilter }}"
            buildConfiguration: 'Release'
            customEnvironment:
            - name: CLIENT_ID
              value: $(CLIENT_ID)
            - name: APP_SECRET
              value: $(app-secret)
            - name: TENANT_ID
              value: $(TENANT_ID)
